[package]
name = "hmt-registry"
version.workspace = true
edition.workspace = true

[dependencies]
# inner dependencies
hmt-manifest.workspace = true

thiserror.workspace = true
reqwest.workspace = true
toml.workspace = true
