[package]
name = "hummanta-manifest"
version.workspace = true
edition.workspace = true

[[bin]]
name = "hummanta-manifest-generator"
path = "bin/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
sha2.workspace = true
target-triple.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "macros", "rt-multi-thread"] }
toml.workspace = true
